AppBundle\Entity\Place:
    attributes:
        id:
            groups: ['place', 'price', 'theme']
        name:
            groups: ['place', 'price', 'theme']
        address:
            groups: ['place', 'price', 'theme']
        prices:
            groups: ['place']
        themes:
            groups: ['place']

AppBundle\Entity\Price:
    attributes:
        id:
            groups: ['place', 'price']
        type:
            groups: ['place', 'price']
        value:
            groups: ['place', 'price']
        place:
            groups: ['price']

AppBundle\Entity\Theme:
    attributes:
        id:
            groups: ['place', 'theme']
        name:
            groups: ['place', 'theme']
        value:
            groups: ['place', 'theme']
        place:
            groups: ['theme']

AppBundle\Entity\Preference:
    attributes:
        id:
            groups: ['preference', 'Users']
        name:
            groups: ['preference', 'Users']
        value:
            groups: ['preference', 'Users']
        user:
            groups: ['preference']

AppBundle\Entity\Users:
    attributes:
        id:
            groups: ['preference', 'Users', 'auth-token']
        firstname:
            groups: ['preference', 'Users', 'auth-token']
        lastname:
            groups: ['preference', 'Users', 'auth-token']
        email:
            groups: ['preference', 'Users', 'auth-token']
        preferences:
            groups: ['Users']

AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdDate:
            groups: ['auth-token']
        user:
            groups: ['auth-token', 'Users']

AppBundle\Entity\Channel:
    attributes:
        id:
            groups: ['channel', 'Users']
        name:
            groups: ['channel', 'Users']
        currentInfo:
            groups: ['channel', 'Users']
        nextInfo:
            groups: ['channel', 'Users']
        user:
            groups: ['channel']
