AppBundle\Entity\Preference:
    exclusion_policy: none
    properties:
        id:
            groups: ['preference', 'Users']
        name:
            groups: ['preference', 'Users']
        value:
            groups: ['preference', 'Users']
        user:
            groups: ['preference']