AppBundle\Entity\AuthToken:
    exclusion_policy: none
    properties:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdDate:
            groups: ['auth-token']
        user:
            groups: ['auth-token', 'Users']